<<<<<<< Updated upstream
name: Build wheels and sdist and upload to PyPI
=======
name: Build wheels and sdist and upload to PyPi
>>>>>>> Stashed changes

on:
  workflow_dispatch:
  release:
    types:
      - published
<<<<<<< Updated upstream
=======
  # push:
    # branches:
      # toml_setup_updates
      # For debugging.
>>>>>>> Stashed changes

jobs:
  build_sdist:
    name: Build platform-independent wheel and sdist and upload to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
<<<<<<< Updated upstream
          python -m pip install -U pip

          pip install -U numpy setuptools wheel
=======
          python -m pip install -U pip setuptools wheel build
>>>>>>> Stashed changes
          pip install -U -r requirements.txt

      - name: Build wheel
        run: |
          pip wheel -w wheels .
          ls -l wheels

      - name: Build sdist
        run: |
          python setup.py sdist
          cp wheels/fast-pt* dist
          ls -l dist
          tar tvfz dist/fast-pt-*.tar.gz

<<<<<<< Updated upstream
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: jablazek
            password: ${{ secrets.pypi_password }}
            verbose: true
=======
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
>>>>>>> Stashed changes
