name: Build wheels and sdist and upload to TestPyPI

on:
  push:
    branches:
      toml_setup_updates
 
  # workflow_dispatch:
  # release:
    # types:
    #  - published


jobs:
  build_sdist:
    name: Build platform-independent wheel and sdist and upload to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U numpy setuptools wheel
          pip install -U -r requirements.txt

      - name: Build wheel and sdist
        run: |
          python -m build

      - name: Upload distributions as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          verbose: true
